services:
  obsidian:
    build:
      context: .
      dockerfile: obsidian.Dockerfile
    container_name: obsidian
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - CUSTOM_USER=admin
      - PASSWORD=password
      - LC_ALL=ja_JP.UTF-8
      - GTK_IM_MODULE=fcitx5
      - QT_IM_MODULE=fcitx5
      - XMODIFIERS=@im=fcitx5
    volumes:
      - ./config:/config
      - ./vaults:/config/vaults
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped

  # mcp-obsidian:
  #   image: mcp/obsidian
  #   container_name: mcp-obsidian
  #   volumes:
  #     # obsidianサービスとvaultsディレクトリを共有
  #     - ./vaults:/vault
  #   environment:
  #     # コンテナ内のObsidian Vaultへのパスを指定 (image仕様の仮定)
  #     - OBSIDIAN_VAULT_PATH=/vault
  #   env_file:
  #     - .env.mcp
  #   restart: unless-stopped

  writer:
    build:
      context: .
      dockerfile: writer.Dockerfile
    volumes:
      # プロジェクト全体をマウントして、gordon-mcp.ymlや他のファイルにアクセスできるようにする
      - .:/workspace
    working_dir: /workspace
    env_file:
      - .env.writer
    # コンテナ内でインタラクティブなシェルを操作するために必要
    tty: true
    stdin_open: true
    restart: unless-stopped
